vim.pack.add { 'https://github.com/folke/tokyonight.nvim' }
vim.cmd.colorscheme 'tokyonight-night'
-- return {
--   {
--     'ThePrimeagen/harpoon',
--     branch = 'harpoon2',
--     dependencies = {
--       'nvim-lua/plenary.nvim',
--     },
--     config = function()
--       require('harpoon'):setup()
--     end,
--     keys = {
--       {
--         '<leader>a',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon:list():add()
--         end,
--         desc = 'Add to Harpoon',
--       },
--       {
--         '<C-e>',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon.ui:toggle_quick_menu(harpoon:list())
--         end,
--         desc = 'Toggle Harpoon Quick Menu',
--       },
--       {
--         '<leader>hq',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon:list():select(1)
--         end,
--         desc = 'which_key_ignore',
--       },
--       {
--         '<leader>hw',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon:list():select(2)
--         end,
--         desc = 'which_key_ignore',
--       },
--       {
--         '<leader>hf',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon:list():select(3)
--         end,
--         desc = 'which_key_ignore',
--       },
--       {
--         '<leader>hp',
--         function()
--           local harpoon = require 'harpoon'
--           harpoon:list():select(4)
--         end,stat:q
-- 
--         desc = 'which_key_ignore',
--       },
--     },
--   },
--   { 'taybart/b64.nvim' },
-- 
--   { -- Adds git related signs to the gutter, as well as utilities for managing changes
--     'lewis6991/gitsigns.nvim',
--     opts = {
--       signs = {
--         add = { text = '+' },
--         change = { text = '~' },
--         delete = { text = '_' },
--         topdelete = { text = '‾' },
--         changedelete = { text = '~' },
--       },
--     },
--   },
-- }
